#!/usr/bin/env python3
"""
test_schema.py — the messages.kind/meta migration.

    python3 tests/test_schema.py

Covers the thing that actually bites: the migration runs on every connect
against real databases that already have data in them, so it has to be
idempotent and it must not disturb rows it doesn't understand.

Also pins the coupling between commands.py (which writes the :remember marker)
and db.py (which parses it). That pairing has broken silently once already —
see BACKLOG.md.
"""
import json
import sqlite3
import sys
import tempfile
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
sys.path.insert(0, str(ROOT))
sys.dont_write_bytecode = True

PASS, FAIL = [], []


def ok(name, cond, detail=""):
    (PASS if cond else FAIL).append(name)
    print(f"  {'ok  ' if cond else 'FAIL'} {name}")
    if not cond and detail:
        print(f"       {detail}")


def legacy_db(path):
    """A database as it looked before kind/meta existed, with real rows."""
    c = sqlite3.connect(path)
    c.executescript("""
        CREATE TABLE sessions (
            id INTEGER PRIMARY KEY, title TEXT, model TEXT, provider TEXT,
            created_at TEXT, updated_at TEXT);
        CREATE TABLE messages (
            id INTEGER PRIMARY KEY, session_id INTEGER, role TEXT,
            content TEXT, model TEXT, tokens_in INTEGER, tokens_out INTEGER,
            created_at TEXT);
        CREATE TABLE tags (id INTEGER PRIMARY KEY, name TEXT UNIQUE);
        CREATE TABLE session_tags (session_id INTEGER, tag_id INTEGER,
            PRIMARY KEY (session_id, tag_id));
    """)
    c.execute("INSERT INTO sessions (id,title) VALUES (1,'s')")
    c.executemany(
        "INSERT INTO messages (session_id, role, content) VALUES (?,?,?)",
        [(1, "user", "a normal question"),
         (1, "assistant", "a normal answer"),
         (1, "user", '[:remember "what did we decide" → 8 excerpts '
                     'injected (ephemeral)]'),
         (1, "user", "[:remember but not really a marker]"),
         (1, "user", '[:remember "multi\nline query" → 3 excerpts '
                     'injected (ephemeral)]')])
    c.commit()
    c.close()


def main():
    tmp = Path(tempfile.mkdtemp())
    path = tmp / "chat.db"
    legacy_db(path)

    import db as dbmod
    dbmod.DB_PATH = path

    conn = dbmod.db()          # runs the migration
    cols = [r[1] for r in conn.execute("PRAGMA table_info(messages)")]
    ok("kind column added", "kind" in cols)
    ok("meta column added", "meta" in cols)

    rows = dict(conn.execute("SELECT content, kind FROM messages"))
    ok("normal message -> chat",
       rows["a normal question"] == "chat", rows.get("a normal question"))
    ok("assistant message -> chat",
       rows["a normal answer"] == "chat")

    marker = '[:remember "what did we decide" → 8 excerpts injected (ephemeral)]'
    ok("marker -> recall_marker", rows[marker] == "recall_marker", rows.get(marker))

    meta = conn.execute("SELECT meta FROM messages WHERE content=?",
                        (marker,)).fetchone()[0]
    m = json.loads(meta)
    ok("marker meta carries the query", m.get("query") == "what did we decide", meta)
    ok("marker meta carries the count", m.get("excerpts") == 8, meta)

    lookalike = "[:remember but not really a marker]"
    ok("lookalike left as chat", rows[lookalike] == "chat", rows.get(lookalike))
    ok("lookalike has no meta",
       conn.execute("SELECT meta FROM messages WHERE content=?",
                    (lookalike,)).fetchone()[0] is None)

    multi = [c for c in rows if "multi\nline" in c][0]
    ok("multi-line query marker matched", rows[multi] == "recall_marker")

    ok("nothing left NULL",
       conn.execute("SELECT COUNT(*) FROM messages WHERE kind IS NULL"
                    ).fetchone()[0] == 0)
    conn.close()

    print("\n--- idempotency: the migration runs on every single connect ---")
    before = sqlite3.connect(path).execute(
        "SELECT id, kind, meta FROM messages ORDER BY id").fetchall()
    for _ in range(3):
        dbmod.db().close()
    after = sqlite3.connect(path).execute(
        "SELECT id, kind, meta FROM messages ORDER BY id").fetchall()
    ok("three more connects change nothing", before == after)

    print("\n--- routine sessions get provider='routine', and only routine sessions ---")
    # The marker replaces "the title starts with 'routine:'", which is not
    # data. The backfill has to be narrow: a hand-written chat whose title
    # merely *starts* that way must survive, or the hub silently hides a real
    # conversation. Every case here is a title a human could plausibly type.
    conn = dbmod.db()
    cases = [
        ("routine: Heartbeat — 2026-07-20 19:13", "routine", "generated by runner.py"),
        ("routine: Propose test — 2026-07-21 07:51", "routine", "another real one"),
        ("routine: ideas", dbmod.PROVIDER_CHAT, "no timestamp — a human title"),
        ("routine: notes — how they work", dbmod.PROVIDER_CHAT, "em dash, no timestamp"),
        ("my routine: Heartbeat — 2026-07-20 19:13", dbmod.PROVIDER_CHAT, "prefix not at the start"),
        ("Normal chat about routines", dbmod.PROVIDER_CHAT, "unrelated"),
    ]
    for title, _, _ in cases:
        dbmod.new_session(conn, title=title)
    conn.close()

    conn = dbmod.db()   # reconnecting is what runs the migration
    for title, expect, why in cases:
        got = conn.execute("SELECT provider FROM sessions WHERE title=?",
                           (title,)).fetchone()[0]
        ok(f"{why}: {expect}", got == expect, f"{title!r} -> {got}")

    # A routine run created *now* must be marked at insert, not rely on the
    # backfill — the backfill is for history and will find nothing next start.
    rid = dbmod.new_session(conn, title="fresh run",
                            provider=dbmod.PROVIDER_ROUTINE)
    ok("new_session(provider=PROVIDER_ROUTINE) marks it at insert",
       conn.execute("SELECT provider FROM sessions WHERE id=?",
                    (rid,)).fetchone()[0] == "routine")

    before = conn.execute("SELECT id, provider FROM sessions ORDER BY id").fetchall()
    conn.close()
    for _ in range(3):
        dbmod.db().close()
    conn = dbmod.db()
    after = conn.execute("SELECT id, provider FROM sessions ORDER BY id").fetchall()
    ok("the routine backfill is idempotent too", before == after)

    # chunk.py derives a chunk's `source` from the session's provider. The rule
    # is "wiki if provider == 'wiki' else chat", so a routine transcript indexes
    # as source='chat' — the same as before the marker existed. Pinned because
    # it is a coupling nobody would think to check when editing either file.
    import inspect as _inspect
    import chunk as chunkmod
    src = _inspect.getsource(chunkmod)
    ok("chunk.py still keys source off 'wiki' only, so routine -> 'chat'",
       "'wiki' if provider == 'wiki' else 'chat'" in src
       or '"wiki" if provider == "wiki" else "chat"' in src, src[:0])
    conn.close()

    print("\n--- a marker written by the real code must parse here ---")
    # The regex in db.py hard-codes commands.py's marker format. Build one the
    # way commands.py builds it and assert db.py still recognises it.
    import commands, inspect
    src = inspect.getsource(commands.do_remember)
    ok("commands.py still builds the marker this way",
       'f\'[:remember "{query}" → {len(hits)} excerpts \'' in src
       or "[:remember" in src,
       "do_remember no longer contains a recognisable marker literal")

    query, n = "a live query", 4
    real_marker = (f'[:remember "{query}" → {n} excerpts '
                   f'injected (ephemeral)]')
    m2 = dbmod._MARKER_RE.match(real_marker)
    ok("db.py parses the marker commands.py writes", m2 is not None,
       f"db._MARKER_RE failed on: {real_marker!r}")
    if m2:
        ok("parsed query round-trips", m2.group("query") == query)
        ok("parsed count round-trips", int(m2.group("n")) == n)

    print("\n--- a fresh database gets the columns too ---")
    fresh = tmp / "fresh.db"
    dbmod.DB_PATH = fresh
    c = dbmod.db()
    cols = [r[1] for r in c.execute("PRAGMA table_info(messages)")]
    ok("fresh db has kind", "kind" in cols)
    ok("fresh db has meta", "meta" in cols)
    c.close()

    print("\n--- the First Message columns migrate onto an existing db too ---")
    # A normal connection and db(":memory:") must use the same schema
    # (decision 10) — proven here by running the same migration against a
    # legacy on-disk db (built with no first_message_* columns at all) and a
    # fresh :memory: connection, and checking both end up identical.
    legacy2 = tmp / "legacy2.db"
    legacy_db(legacy2)
    dbmod.DB_PATH = legacy2
    disk_conn = dbmod.db()
    mem_conn = dbmod.db(":memory:")
    disk_cols = sorted(r[1] for r in
                       disk_conn.execute("PRAGMA table_info(sessions)"))
    mem_cols = sorted(r[1] for r in
                      mem_conn.execute("PRAGMA table_info(sessions)"))
    ok("a migrated on-disk db and a fresh :memory: db have the same columns",
       disk_cols == mem_cols, (disk_cols, mem_cols))
    for c in ("first_message_name", "first_message_text", "first_message_at"):
        ok(f"{c} is on the disk connection", c in disk_cols)
        ok(f"{c} is on the memory connection", c in mem_cols)

    print("\n--- get/set_first_message ---")
    sid = dbmod.new_session(disk_conn, title="fm")
    ok("no snapshot yet", dbmod.get_first_message(disk_conn, sid) is None)
    ok("has_chat_messages is false for an empty session",
       dbmod.has_chat_messages(disk_conn, sid) is False)

    dbmod.set_first_message(disk_conn, sid, "muse.md", "Good evening.",
                            at="2026-07-31T09:00:00+00:00")
    snap = dbmod.get_first_message(disk_conn, sid)
    ok("snapshot round-trips: name", snap["name"] == "muse.md", snap)
    ok("snapshot round-trips: text", snap["text"] == "Good evening.", snap)
    ok("snapshot round-trips: at", snap["at"] == "2026-07-31T09:00:00+00:00",
       snap)

    dbmod.save_message(disk_conn, sid, "user", "hello", kind="chat")
    ok("has_chat_messages is true once a chat row exists",
       dbmod.has_chat_messages(disk_conn, sid) is True)

    # kind='attachment' is not a chat turn — First Message eligibility and
    # /continue's refusal both key off has_chat_messages precisely so an
    # attach doesn't count as the conversation starting.
    sid2 = dbmod.new_session(disk_conn, title="fm2")
    dbmod.save_message(disk_conn, sid2, "user", "a file", kind="attachment")
    ok("an attachment is not a chat turn",
       dbmod.has_chat_messages(disk_conn, sid2) is False)

    print("\n--- count_chat_user_turns: the governor's cadence clock ---")
    sid3 = dbmod.new_session(disk_conn, title="cadence")
    ok("zero turns in a fresh session",
       dbmod.count_chat_user_turns(disk_conn, sid3) == 0)
    dbmod.save_message(disk_conn, sid3, "user", "one", kind="chat")
    dbmod.save_message(disk_conn, sid3, "assistant", "reply", kind="chat")
    ok("the assistant row does not count",
       dbmod.count_chat_user_turns(disk_conn, sid3) == 1)
    dbmod.save_message(disk_conn, sid3, "user", "two", kind="chat")
    ok("a second user turn advances the count",
       dbmod.count_chat_user_turns(disk_conn, sid3) == 2)
    # OOC and /continue add no user row at all — governor.py's contract — so
    # the only way to prove they don't advance the count is that nothing
    # simulating them (a tool_call/tool_result/attachment/recall_marker row)
    # does either.
    dbmod.save_message(disk_conn, sid3, "user", "a file", kind="attachment")
    dbmod.save_message(disk_conn, sid3, "user",
                       '[:remember "x" → 1 excerpts injected (ephemeral)]',
                       kind="recall_marker")
    ok("attachments and recall markers are machinery, not conversation",
       dbmod.count_chat_user_turns(disk_conn, sid3) == 2)
    disk_conn.close()
    mem_conn.close()

    print("\n--- deleting reaches the index that points at what was deleted ---")
    # chunks/vec_chunks are an index over messages with no foreign key to
    # enforce it, so the cascade is code. Three failures, and only the first
    # was ever reported: deleted content left in the retrieval index, orphaned
    # rows, and — the dangerous one — SQLite reusing a deleted rowid so a stale
    # chunk joins cleanly to an unrelated live message.
    import sqlite_vec

    def seeded(path):
        """A db with two sessions, messages, chunks and vectors for both."""
        dbmod.DB_PATH = path
        c = dbmod.db()
        # chunks is built by chunk.py, not by db()'s migration — the index is
        # deliberately not part of the core schema.
        import chunk as chunkmod
        chunkmod.ensure_table(c, rebuild=False)
        c.enable_load_extension(True)
        sqlite_vec.load(c)
        c.enable_load_extension(False)
        c.execute("CREATE VIRTUAL TABLE IF NOT EXISTS vec_chunks USING vec0("
                  "chunk_id integer primary key, embedding float[4])")
        c.execute("INSERT INTO sessions (id,title) VALUES (1,'keep')")
        c.execute("INSERT INTO sessions (id,title) VALUES (2,'doomed')")
        for sid, body in ((1, "kept text"), (2, "doomed text")):
            for i in range(2):
                cur = c.execute(
                    "INSERT INTO messages (session_id,role,content) "
                    "VALUES (?,?,?)", (sid, "user", f"{body} {i}"))
                mid = cur.lastrowid
                c.execute("INSERT INTO chunks (message_id,session_id,kind,"
                          "ordinal,text,token_est,source) "
                          "VALUES (?,?,'message',0,?,3,'chat')",
                          (mid, sid, f"{body} {i}"))
                cid = c.execute("SELECT id FROM chunks WHERE message_id=?",
                                (mid,)).fetchone()[0]
                c.execute("INSERT INTO vec_chunks (chunk_id,embedding) "
                          "VALUES (?,?)", (cid, sqlite_vec.serialize_float32(
                              [0.1, 0.2, 0.3, 0.4])))
        c.commit()
        return c

    c = seeded(tmp / "cascade.db")
    dbmod.delete_session(c, 2)
    ok("the deleted session's chunks are gone",
       c.execute("SELECT COUNT(*) FROM chunks WHERE session_id=2"
                 ).fetchone()[0] == 0)
    ok("...and so are its vectors — a delete that leaves the content "
       "answering queries is not a delete",
       c.execute("SELECT COUNT(*) FROM vec_chunks v LEFT JOIN chunks c "
                 "ON c.id=v.chunk_id WHERE c.id IS NULL").fetchone()[0] == 0)
    ok("the other session is untouched",
       c.execute("SELECT COUNT(*) FROM chunks WHERE session_id=1"
                 ).fetchone()[0] == 2)
    ok("...with its vectors",
       c.execute("SELECT COUNT(*) FROM vec_chunks").fetchone()[0] == 2)

    # The mis-attribution regression, end to end: delete the top session, then
    # write a new message that takes a freed rowid. Before the cascade, the
    # stale chunk followed that id into a live session.
    fresh_mid = c.execute(
        "INSERT INTO messages (session_id,role,content) VALUES (1,'user','new')"
    ).lastrowid
    c.commit()
    ok("a reused rowid inherits no stale chunk",
       c.execute("SELECT COUNT(*) FROM chunks WHERE message_id=?",
                 (fresh_mid,)).fetchone()[0] == 0)
    ok("no chunk disagrees with its message about the session",
       c.execute("SELECT COUNT(*) FROM chunks c JOIN messages m "
                 "ON m.id=c.message_id WHERE m.session_id != c.session_id"
                 ).fetchone()[0] == 0)
    c.close()

    print("\n--- delete_message drops its index rows too ---")
    c = seeded(tmp / "delmsg.db")
    mid = c.execute("SELECT id FROM messages WHERE session_id=2").fetchone()[0]
    dbmod.delete_message(c, mid)
    ok("its chunks are gone",
       c.execute("SELECT COUNT(*) FROM chunks WHERE message_id=?",
                 (mid,)).fetchone()[0] == 0)
    ok("its vectors are gone",
       c.execute("SELECT COUNT(*) FROM vec_chunks").fetchone()[0] == 3)
    c.close()

    print("\n--- the repair pass for databases already damaged ---")
    c = seeded(tmp / "repair.db")
    ok("a healthy db has nothing stale", dbmod.find_stale_chunks(c) == ([], []))

    # Reproduce both shapes of damage the way the old code produced them:
    # delete rows from messages/sessions directly, leaving the index behind.
    c.execute("DELETE FROM messages WHERE session_id=2")
    c.execute("DELETE FROM sessions WHERE id=2")
    # ...and one mis-attributed chunk: its message exists, but says otherwise.
    live = c.execute("SELECT id FROM messages WHERE session_id=1").fetchone()[0]
    c.execute("INSERT INTO chunks (message_id,session_id,kind,ordinal,text,"
              "token_est,source) VALUES (?,?,'message',9,'stale',1,'chat')",
              (live, 99))
    c.commit()

    gone, mis = dbmod.find_stale_chunks(c)
    ok("orphaned chunks are found", len(gone) == 2, gone)
    ok("mis-attributed chunks are found too — a count of orphans understates "
       "the damage", len(mis) == 1, mis)

    n, v = dbmod.prune_stale_chunks(c)
    ok("the prune removes exactly those", (n, v) == (3, 2), (n, v))
    ok("...and is idempotent", dbmod.prune_stale_chunks(c) == (0, 0))
    ok("healthy chunks survived",
       c.execute("SELECT COUNT(*) FROM chunks").fetchone()[0] == 2)
    ok("healthy vectors survived",
       c.execute("SELECT COUNT(*) FROM vec_chunks").fetchone()[0] == 2)
    ok("messages were not touched by a repair of the index",
       c.execute("SELECT COUNT(*) FROM messages").fetchone()[0] == 2)
    c.close()

    print("\n--- create_chat: a chosen positive id, never a competing "
          "auto-increment ---")
    c = dbmod.db(":memory:")
    new_id = dbmod.create_chat(c, 501)
    ok("returns the chosen id", new_id == 501, new_id)
    row = c.execute("SELECT title, provider FROM sessions WHERE id=501"
                    ).fetchone()
    ok("created as an ordinary chat", row == ("(untitled)", dbmod.PROVIDER_CHAT),
       row)

    for bad in (0, -3, "5", 5.0, True):
        try:
            dbmod.create_chat(c, bad)
            ok(f"chat_id={bad!r} refused", False, "did not raise")
        except ValueError:
            ok(f"chat_id={bad!r} refused", True)

    for label, kind_provider in (
        ("another chat", dbmod.PROVIDER_CHAT),
        ("a wiki row", dbmod.PROVIDER_WIKI),
        ("a routine row", dbmod.PROVIDER_ROUTINE),
    ):
        occupied = dbmod.new_session(c, title="occupant", provider=kind_provider)
        try:
            dbmod.create_chat(c, occupied)
            ok(f"collision with {label} refused", False, "did not raise")
        except dbmod.ChatIdTaken as e:
            ok(f"collision with {label} refused", e.args[0] == occupied)
        # never opened, renamed or replaced the occupant
        ok(f"...and the occupant is untouched",
           c.execute("SELECT title, provider FROM sessions WHERE id=?",
                    (occupied,)).fetchone() == ("occupant", kind_provider))
    c.close()

    print("\n--- resolve_delete_target: identity, never an editable title ---")
    c = dbmod.db(":memory:")
    chat_id = dbmod.new_session(c, title="ordinary")
    target = dbmod.resolve_delete_target(c, chat_id)
    ok("resolves an ordinary chat", target == {
        "id": chat_id, "title": "ordinary", "is_main": False,
        "message_count": 0}, target)

    main_id, _ = dbmod.get_or_create_main(c, "muse.md", "hi")
    target = dbmod.resolve_delete_target(c, "MAIN")
    ok("resolves Main case-insensitively by identity",
       target["id"] == main_id and target["is_main"] is True, target)

    # A hand-edited title reading "main" must not resolve as Main by text —
    # only 'main' the literal token does, and only through provider identity.
    fake_id = dbmod.new_session(c, title="main")
    target = dbmod.resolve_delete_target(c, fake_id)
    ok("a chat titled 'main' is not Main",
       target["is_main"] is False and target["id"] == fake_id, target)

    try:
        dbmod.resolve_delete_target(c, 999999)
        ok("a missing id refuses", False, "did not raise")
    except dbmod.DeleteTargetError:
        ok("a missing id refuses", True)

    wiki_id = dbmod.new_session(c, title="a wiki page",
                                provider=dbmod.PROVIDER_WIKI)
    try:
        dbmod.resolve_delete_target(c, wiki_id)
        ok("a wiki row refuses as not-a-chat", False, "did not raise")
    except dbmod.DeleteTargetError as e:
        ok("a wiki row refuses as not-a-chat", True, str(e))

    routine_id = dbmod.new_session(c, title="a routine run",
                                   provider=dbmod.PROVIDER_ROUTINE)
    try:
        dbmod.resolve_delete_target(c, routine_id)
        ok("a routine row refuses as not-a-chat", False, "did not raise")
    except dbmod.DeleteTargetError:
        ok("a routine row refuses as not-a-chat", True)
    c.close()

    print("\n--- classify_latest_turn: the four repair-boundary states ---")
    c = dbmod.db(":memory:")
    sid = dbmod.new_session(c, title="repair")
    state, uid, aids = dbmod.classify_latest_turn(c, sid)
    ok("no user row -> nothing_sent",
       (state, uid, aids) == (dbmod.TURN_NOTHING_SENT, None, []),
       (state, uid, aids))

    dbmod.save_message(c, sid, "user", "hello", kind="chat")
    u1 = c.execute("SELECT id FROM messages WHERE session_id=? AND role='user' "
                   "ORDER BY id DESC LIMIT 1", (sid,)).fetchone()[0]
    state, uid, aids = dbmod.classify_latest_turn(c, sid)
    ok("a user row with nothing after -> unanswered",
       (state, uid, aids) == (dbmod.TURN_UNANSWERED, u1, []), (state, uid, aids))

    # An empty retry artefact (agent._finish("") on an empty-completion 400)
    # is a kind='chat', role='assistant' row with no content — still
    # unanswered, not completed.
    dbmod.save_message(c, sid, "assistant", "", kind="chat")
    state, uid, aids = dbmod.classify_latest_turn(c, sid)
    ok("an empty answer row is still unanswered", state == dbmod.TURN_UNANSWERED,
       (state, aids))
    empty_id = c.execute("SELECT id FROM messages WHERE session_id=? "
                         "ORDER BY id DESC LIMIT 1", (sid,)).fetchone()[0]
    ok("...and is itself part of the answer side", aids == [empty_id], aids)

    # A tool call + result in between, then a real final answer -> completed.
    dbmod.save_message(c, sid, "assistant", "", kind="tool_call",
                       meta={"tool_calls": [{"id": "t1", "function":
                             {"name": "read_file", "arguments": "{}"}}]})
    dbmod.save_message(c, sid, "tool", "the file", kind="tool_result",
                       meta={"tool": "read_file", "tool_call_id": "t1"})
    dbmod.save_message(c, sid, "assistant", "here you go", kind="chat")
    state, uid, aids = dbmod.classify_latest_turn(c, sid)
    ok("tool calls + one real answer -> completed",
       state == dbmod.TURN_COMPLETED and uid == u1, (state, uid))
    ok("...and the answer side carries all four later rows",
       len(aids) == 4, aids)

    # Attachments and recall markers interleaved afterward are context, not
    # sends, and must never appear in the answer side.
    dbmod.save_message(c, sid, "user", "a file", kind="attachment")
    dbmod.save_message(c, sid, "user",
                       '[:remember "x" → 1 excerpts injected (ephemeral)]',
                       kind="recall_marker")
    state, uid, aids2 = dbmod.classify_latest_turn(c, sid)
    ok("attachments/recall markers never enter the answer side",
       aids2 == aids, (aids, aids2))

    # A later /continue or OOC answer (another assistant kind='chat' row, no
    # new user row) makes the turn ambiguous.
    dbmod.save_message(c, sid, "assistant", "continued", kind="chat")
    state, uid, aids3 = dbmod.classify_latest_turn(c, sid)
    ok("two final answers -> ambiguous", state == dbmod.TURN_AMBIGUOUS,
       (state, aids3))
    c.close()

    print("\n--- turn_tool_names reads persisted tool_call meta ---")
    c = dbmod.db(":memory:")
    sid = dbmod.new_session(c, title="tools")
    dbmod.save_message(c, sid, "user", "write it", kind="chat")
    dbmod.save_message(c, sid, "assistant", "", kind="tool_call",
                       meta={"tool_calls": [
                           {"id": "a", "function": {"name": "read_file"}},
                           {"id": "b", "function": {"name": "write_file"}},
                       ]})
    _, _, aids = dbmod.classify_latest_turn(c, sid)
    names = dbmod.turn_tool_names(c, aids)
    ok("both call names come back, in order",
       names == ["read_file", "write_file"], names)
    ok("an empty id list is a no-op", dbmod.turn_tool_names(c, []) == [])
    c.close()

    print("\n--- prune_turn: keep_user (/swipe) vs full prune (/undo), "
          "with chunks and vectors ---")
    import sqlite_vec
    import chunk as chunkmod

    def seeded_turn(path):
        dbmod.DB_PATH = path
        c = dbmod.db()
        chunkmod.ensure_table(c, rebuild=False)
        c.enable_load_extension(True)
        sqlite_vec.load(c)
        c.enable_load_extension(False)
        c.execute("CREATE VIRTUAL TABLE IF NOT EXISTS vec_chunks USING vec0("
                  "chunk_id integer primary key, embedding float[4])")
        sid = dbmod.new_session(c, title="prune-me")
        dbmod.save_message(c, sid, "user", "hello", kind="chat")
        uid = c.execute("SELECT id FROM messages WHERE session_id=? "
                        "ORDER BY id DESC LIMIT 1", (sid,)).fetchone()[0]
        dbmod.save_message(c, sid, "assistant", "hi there", kind="chat")
        aid = c.execute("SELECT id FROM messages WHERE session_id=? "
                        "ORDER BY id DESC LIMIT 1", (sid,)).fetchone()[0]
        for mid, text in ((uid, "hello"), (aid, "hi there")):
            cur = c.execute(
                "INSERT INTO chunks (message_id,session_id,kind,ordinal,"
                "text,token_est,source) VALUES (?,?,'message',0,?,3,'chat')",
                (mid, sid, text))
            cid = cur.lastrowid
            c.execute("INSERT INTO vec_chunks (chunk_id,embedding) VALUES (?,?)",
                      (cid, sqlite_vec.serialize_float32([0.1, 0.2, 0.3, 0.4])))
        c.commit()
        return c, sid, uid, aid

    c, sid, uid, aid = seeded_turn(tmp / "prune_swipe.db")
    dbmod.prune_turn(c, uid, [aid], keep_user=True)
    ok("swipe: the user row survives",
       c.execute("SELECT COUNT(*) FROM messages WHERE id=?",
                (uid,)).fetchone()[0] == 1)
    ok("swipe: the answer row is gone",
       c.execute("SELECT COUNT(*) FROM messages WHERE id=?",
                (aid,)).fetchone()[0] == 0)
    ok("swipe: its chunk is gone too",
       c.execute("SELECT COUNT(*) FROM chunks WHERE message_id=?",
                (aid,)).fetchone()[0] == 0)
    ok("swipe: and its vector",
       c.execute("SELECT COUNT(*) FROM vec_chunks").fetchone()[0] == 1)
    c.close()

    c, sid, uid, aid = seeded_turn(tmp / "prune_undo.db")
    dbmod.prune_turn(c, uid, [aid], keep_user=False)
    ok("undo: both rows are gone",
       c.execute("SELECT COUNT(*) FROM messages WHERE session_id=?",
                (sid,)).fetchone()[0] == 0)
    ok("undo: no chunks remain for this session",
       c.execute("SELECT COUNT(*) FROM chunks WHERE session_id=?",
                (sid,)).fetchone()[0] == 0)
    ok("undo: no vectors remain",
       c.execute("SELECT COUNT(*) FROM vec_chunks").fetchone()[0] == 0)
    c.close()

    print("\n--- a forced vector-delete failure rolls back the whole "
          "operation (delete_session and prune_turn alike) ---")
    c, sid, uid, aid = seeded_turn(tmp / "prune_fail.db")
    real_drop = dbmod.drop_chunks

    def boom(conn, chunk_ids):
        raise RuntimeError("sqlite-vec unavailable")

    dbmod.drop_chunks = boom
    try:
        try:
            dbmod.prune_turn(c, uid, [aid], keep_user=False)
            ok("prune_turn propagates the failure", False, "did not raise")
        except RuntimeError:
            ok("prune_turn propagates the failure", True)
        ok("...and nothing was deleted — both rows survive",
           c.execute("SELECT COUNT(*) FROM messages WHERE session_id=?",
                    (sid,)).fetchone()[0] == 2)
        ok("...its chunks survive too",
           c.execute("SELECT COUNT(*) FROM chunks WHERE session_id=?",
                    (sid,)).fetchone()[0] == 2)

        try:
            dbmod.delete_session(c, sid)
            ok("delete_session propagates the same failure", False,
               "did not raise")
        except RuntimeError:
            ok("delete_session propagates the same failure", True)
        ok("...and the session is still there, untouched",
           c.execute("SELECT COUNT(*) FROM sessions WHERE id=?",
                    (sid,)).fetchone()[0] == 1)
    finally:
        dbmod.drop_chunks = real_drop
    c.close()

    print("\n--- B-1.5.1-01a: a current-schema populated database opens "
          "without retaining a writer ---")
    # The bug: every connect ran an UPDATE unconditionally, even when nothing
    # matched its WHERE clause — and SQLite takes the write lock the moment an
    # UPDATE opens, whether or not a row is found. A scheduled tick opening
    # the database while a chat holds it could exhaust its busy timeout and
    # die with no routine run at all. Guard each write with a check first, so
    # the overwhelmingly common case — a database that is already current —
    # does no writing.
    current = tmp / "current.db"
    dbmod.DB_PATH = current
    seed = dbmod.db()          # first connect: creates + migrates fresh
    sid = dbmod.new_session(seed, title="s")
    dbmod.save_message(seed, sid, "user", "hello", kind="chat")
    dbmod.save_message(seed, sid, "assistant", "hi", kind="chat")
    dbmod.save_message(
        seed, sid, "user",
        '[:remember "already classified" → 2 excerpts injected (ephemeral)]',
        kind="recall_marker",
        meta={"query": "already classified", "excerpts": 2})
    seed.close()

    before = sqlite3.connect(current).execute(
        "SELECT id, kind, meta FROM messages ORDER BY id").fetchall()

    reopened = dbmod.db()
    ok("re-opening a current, populated database leaves conn.in_transaction "
       "False — no writer retained", reopened.in_transaction is False)
    after = reopened.execute(
        "SELECT id, kind, meta FROM messages ORDER BY id").fetchall()
    ok("...and the data is unchanged", before == after, (before, after))
    reopened.close()

    print("\n--- a legacy database still acquires the columns and both "
          "real backfills, guard or no guard ---")
    legacy3 = tmp / "legacy3.db"
    legacy_db(legacy3)
    dbmod.DB_PATH = legacy3
    conn = dbmod.db()
    cols = {r[1] for r in conn.execute("PRAGMA table_info(messages)")}
    ok("legacy-column: kind added under the guarded path", "kind" in cols)
    ok("legacy-column: meta added under the guarded path", "meta" in cols)
    ok("legacy-column: nothing left NULL",
       conn.execute("SELECT COUNT(*) FROM messages WHERE kind IS NULL"
                    ).fetchone()[0] == 0)
    marker = ('[:remember "what did we decide" → 8 excerpts '
              'injected (ephemeral)]')
    ok("recall-marker: still reclassified under the guarded path",
       conn.execute("SELECT kind FROM messages WHERE content=?",
                    (marker,)).fetchone()[0] == "recall_marker")
    conn.close()

    print("\n--- NULL-kind fixture: columns already present, some rows still "
          "NULL — the backfill UPDATE still runs and commits ---")
    nullkind = tmp / "nullkind.db"
    dbmod.DB_PATH = nullkind
    seed2 = dbmod.db()   # creates the columns
    sid2 = dbmod.new_session(seed2, title="s2")
    seed2.execute(
        "INSERT INTO messages (session_id, role, content, kind) "
        "VALUES (?,?,?,NULL)", (sid2, "user", "predates the default"))
    seed2.commit()
    seed2.close()

    conn2 = dbmod.db()   # reconnecting must find and fix the NULL row
    ok("a NULL kind row is backfilled to 'chat' on the next connect",
       conn2.execute("SELECT kind FROM messages WHERE content=?",
                     ("predates the default",)).fetchone()[0] == "chat")
    ok("...and nothing is left NULL",
       conn2.execute("SELECT COUNT(*) FROM messages WHERE kind IS NULL"
                    ).fetchone()[0] == 0)
    conn2.close()

    print("\n--- the mechanism the guard defends against, shown directly ---")
    # Disabling the guard, in miniature: an UPDATE with a WHERE clause that
    # matches nothing still opens a write transaction in SQLite, which is
    # exactly why the unconditional UPDATE used to hold the lock a scheduled
    # tick could not get. If this ever stopped being true, the guard above
    # would be defending against nothing.
    probe = sqlite3.connect(tmp / "probe.db")
    probe.execute("CREATE TABLE t (id INTEGER PRIMARY KEY, kind TEXT)")
    probe.commit()
    ok("a clean connection starts with no transaction open",
       probe.in_transaction is False)
    probe.execute("UPDATE t SET kind='chat' WHERE kind IS NULL")
    ok("an UPDATE matching zero rows still opens a write transaction — "
       "the reason a guard-free migration can hold the lock",
       probe.in_transaction is True)
    probe.rollback()
    probe.close()

    print("\n--- legacy-routine-session fixture, isolated: the backfill "
          "commits only when a legacy row actually exists ---")
    routinelegacy = tmp / "routinelegacy.db"
    dbmod.DB_PATH = routinelegacy
    seed3 = dbmod.db()
    dbmod.new_session(
        seed3, title="routine: Heartbeat — 2026-07-20 19:13")
    seed3.close()
    conn3 = dbmod.db()
    ok("a legacy routine-titled session is backfilled to provider='routine'",
       conn3.execute(
           "SELECT provider FROM sessions WHERE title=?",
           ("routine: Heartbeat — 2026-07-20 19:13",)).fetchone()[0]
       == dbmod.PROVIDER_ROUTINE)
    conn3.close()

    print(f"\n{len(PASS)} passed, {len(FAIL)} failed")
    if FAIL:
        print("FAILED: " + ", ".join(FAIL))
    return 1 if FAIL else 0


if __name__ == "__main__":
    sys.exit(main())
